-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public.asambleas
(
    id serial NOT NULL,
    tipo character varying(30) COLLATE pg_catalog."default" NOT NULL,
    fecha date NOT NULL,
    hora_inicio time without time zone,
    lugar character varying(200) COLLATE pg_catalog."default",
    quorum_minimo integer,
    estado character varying(30) COLLATE pg_catalog."default" DEFAULT 'programada'::character varying,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT asambleas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.credenciales
(
    id serial NOT NULL,
    padron_id integer NOT NULL,
    descripcion character varying(200) COLLATE pg_catalog."default",
    reimpresion boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    row_version integer,
    creado_por character varying(100) COLLATE pg_catalog."default",
    creado_el timestamp with time zone,
    actualizado_por character varying(100) COLLATE pg_catalog."default",
    actualizado_el timestamp with time zone,
    CONSTRAINT credenciales_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.estados
(
    id serial NOT NULL,
    socio_id integer NOT NULL,
    mora_cc character varying(20) COLLATE pg_catalog."default" NOT NULL,
    mora_sol character varying(20) COLLATE pg_catalog."default" NOT NULL,
    mora_ape character varying(20) COLLATE pg_catalog."default" NOT NULL,
    mora_credito character varying(20) COLLATE pg_catalog."default" NOT NULL,
    mora_cabal character varying(20) COLLATE pg_catalog."default" NOT NULL,
    mora_visa character varying(20) COLLATE pg_catalog."default" NOT NULL,
    row_version integer,
    creado_por character varying(100) COLLATE pg_catalog."default",
    creado_el timestamp with time zone,
    actualizado_por character varying(100) COLLATE pg_catalog."default",
    actualizado_el timestamp with time zone,
    CONSTRAINT estados_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.login_logs
(
    id serial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nombre_completo character varying(150) COLLATE pg_catalog."default",
    ip_address character varying(45) COLLATE pg_catalog."default",
    login_at timestamp with time zone,
    CONSTRAINT login_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.mociones
(
    id serial NOT NULL,
    asamblea_id integer NOT NULL,
    titulo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    tipo_votacion character varying(20) COLLATE pg_catalog."default" DEFAULT 'si_no'::character varying,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT mociones_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.moras
(
    id serial NOT NULL,
    socio_id integer NOT NULL,
    producto character varying(30) COLLATE pg_catalog."default" NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL,
    fecha_consulta date NOT NULL DEFAULT CURRENT_DATE,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT moras_pkey PRIMARY KEY (id),
    CONSTRAINT uq_mora_socio_producto_fecha UNIQUE (socio_id, producto, fecha_consulta)
);

CREATE TABLE IF NOT EXISTS public.opciones_mocion
(
    id serial NOT NULL,
    mocion_id integer NOT NULL,
    texto character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT opciones_mocion_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.padron_asamblea
(
    id serial NOT NULL,
    socio_id integer NOT NULL,
    asamblea_id integer NOT NULL,
    situacion character varying(30) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pendiente'::character varying,
    motivo_inhabilitacion character varying(200) COLLATE pg_catalog."default",
    fecha_acreditacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    row_version integer,
    creado_por character varying(100) COLLATE pg_catalog."default",
    creado_el timestamp with time zone,
    actualizado_por character varying(100) COLLATE pg_catalog."default",
    actualizado_el timestamp with time zone,
    CONSTRAINT padron_asamblea_pkey PRIMARY KEY (id),
    CONSTRAINT uq_padron_socio_asamblea UNIQUE (socio_id, asamblea_id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(200) COLLATE pg_catalog."default",
    row_version integer,
    creado_por character varying(100) COLLATE pg_catalog."default",
    creado_el timestamp with time zone,
    actualizado_por character varying(100) COLLATE pg_catalog."default",
    actualizado_el timestamp with time zone,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.socios
(
    id serial NOT NULL,
    cedula character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nro_socio character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nombres character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apellidos character varying(100) COLLATE pg_catalog."default" NOT NULL,
    fecha_nacimiento date,
    fecha_ingreso date,
    sexo character varying(15) COLLATE pg_catalog."default",
    situacion character varying(50) COLLATE pg_catalog."default" DEFAULT 'activo'::character varying,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    trabajo character varying(100) COLLATE pg_catalog."default",
    agencia character varying(100) COLLATE pg_catalog."default",
    row_version integer,
    creado_por character varying(100) COLLATE pg_catalog."default",
    creado_el timestamp with time zone,
    actualizado_por character varying(100) COLLATE pg_catalog."default",
    actualizado_el timestamp with time zone,
    CONSTRAINT socios_pkey PRIMARY KEY (id),
    CONSTRAINT socios_cedula_key UNIQUE (cedula),
    CONSTRAINT socios_nro_socio_key UNIQUE (nro_socio)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id serial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nombre_completo character varying(150) COLLATE pg_catalog."default",
    activo boolean DEFAULT true,
    rol_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    password_venc timestamp with time zone,
    row_version integer,
    creado_por character varying(100) COLLATE pg_catalog."default",
    creado_el timestamp with time zone,
    actualizado_por character varying(100) COLLATE pg_catalog."default",
    actualizado_el timestamp with time zone,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_email_key UNIQUE (email),
    CONSTRAINT usuarios_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.votos
(
    id serial NOT NULL,
    socio_id integer NOT NULL,
    mocion_id integer NOT NULL,
    opcion_elegida character varying(100) COLLATE pg_catalog."default",
    timestamp_voto timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT votos_pkey PRIMARY KEY (id),
    CONSTRAINT uq_voto_socio_mocion UNIQUE (socio_id, mocion_id)
);

ALTER TABLE IF EXISTS public.credenciales
    ADD CONSTRAINT credenciales_padron_id_fkey FOREIGN KEY (padron_id)
    REFERENCES public.padron_asamblea (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.estados
    ADD CONSTRAINT estados_socio_id_fkey FOREIGN KEY (socio_id)
    REFERENCES public.socios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.mociones
    ADD CONSTRAINT mociones_asamblea_id_fkey FOREIGN KEY (asamblea_id)
    REFERENCES public.asambleas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_mociones_asamblea_id
    ON public.mociones(asamblea_id);

ALTER TABLE IF EXISTS public.moras
    ADD CONSTRAINT moras_socio_id_fkey FOREIGN KEY (socio_id)
    REFERENCES public.socios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_moras_socio_id
    ON public.moras(socio_id);

ALTER TABLE IF EXISTS public.opciones_mocion
    ADD CONSTRAINT opciones_mocion_mocion_id_fkey FOREIGN KEY (mocion_id)
    REFERENCES public.mociones (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.padron_asamblea
    ADD CONSTRAINT padron_asamblea_asamblea_id_fkey FOREIGN KEY (asamblea_id)
    REFERENCES public.asambleas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_padron_asamblea_id
    ON public.padron_asamblea(asamblea_id);

ALTER TABLE IF EXISTS public.padron_asamblea
    ADD CONSTRAINT padron_asamblea_socio_id_fkey FOREIGN KEY (socio_id)
    REFERENCES public.socios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_padron_socio_id
    ON public.padron_asamblea(socio_id);

ALTER TABLE IF EXISTS public.usuarios
    ADD CONSTRAINT usuarios_rol_id_fkey FOREIGN KEY (rol_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.votos
    ADD CONSTRAINT votos_mocion_id_fkey FOREIGN KEY (mocion_id)
    REFERENCES public.mociones (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_votos_mocion_id
    ON public.votos(mocion_id);

ALTER TABLE IF EXISTS public.votos
    ADD CONSTRAINT votos_socio_id_fkey FOREIGN KEY (socio_id)
    REFERENCES public.socios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_votos_socio_id
    ON public.votos(socio_id);

END;
